### ISSUE TITLE
Error spam in console while randomly right clicking on items inside inventories.

### ISSUE THREAD

**Issue by AnonDevia** [Argoneon1810/Force-Pickup-Heavy-Container-with-delay#1]
`LOG  : General     , 1670376283728> 903,526,850> Test Item: 556Clip
LOG  : General     , 1670376283729> 903,526,851> Test Item: nil
LOG  : General     , 1670376283742> 903,526,864> -------------------------------------------------------------
attempted index: 1.0 of non-table: null

LOG  : General     , 1670376283742> 903,526,865> -----------------------------------------
STACK TRACE
-----------------------------------------
function: InventoryObjectContextMenu -- file: Context_pickup.lua line # 99 | MOD: Force Pickup Heavy Container (with delay)
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@3bd37568
function: createMenu -- file: ISInventoryPaneContextMenu.lua line # 787 | Vanilla
function: executePatchedCode -- file: PatchUtil.lua line # 5 | MOD: Susceptible
function: onRightMouseUp -- file: ISInventoryPane.lua line # 1444 | Vanilla

ERROR: General     , 1670376283743> 903,526,865> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: 1.0 of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1670376283743> 903,526,865> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: 1.0 of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
	at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:186)
	at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3080)
	at jdk.internal.reflect.GeneratedMethodAccessor953.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:60)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallBoolean(KahluaThread.java:1924)
	at se.krka.kahlua.integration.LuaCaller.protectedCallBoolean(LuaCaller.java:104)
	at zombie.ui.UIElement.onRightMouseUp(UIElement.java:1458)
	at zombie.ui.UIElement.onRightMouseUp(UIElement.java:1416)
	at zombie.ui.UIManager.update(UIManager.java:910)
	at zombie.GameWindow.logic(GameWindow.java:262)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:681)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1670376283744> 903,526,866> -----------------------------------------
STACK TRACE
-----------------------------------------
function: InventoryObjectContextMenu -- file: Context_pickup.lua line # 99 | MOD: Force Pickup Heavy Container (with delay)
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@3bd37568
function: createMenu -- file: ISInventoryPaneContextMenu.lua line # 787 | Vanilla
function: executePatchedCode -- file: PatchUtil.lua line # 5 | MOD: Susceptible
function: onRightMouseUp -- file: ISInventoryPane.lua line # 1444 | Vanilla`

**This error is randomly thrown when interacting with items in any inventory. At first it was because of a weight removal cheat mod I use for testing, but even after disabling that it still spams. It's almost like it's looking for  the ability to force pickup something I already have equipped? I am unsure. I hope this helps!**

**Comment by Argoneon1810** [comment]
thanks for detailed issue report. I'll get test it out base on your description.

**Comment by Argoneon1810** [comment]
tested with number of items: normal heavy item, heavy bags, nested heavy bags, etc.
But, yet, I couldn't replicate the problem. So a dedicated solution for this problem is still unknown.

However, your log says that in some cases an item that opens a context menu can somehow be nil. (but, HOW?)
Something opened a context menu is an item, but that item is a nil?
I cannot imagine how this could be even happening.

So I just added two lines of code to perform nil check prior to do anything.
Hope this fixed the problem.

I will leave this issue opened still. Please come back if it happens again.
